### ISSUE TITLE
Drone OS BV Issue

### ISSUE THREAD

**Issue by Maelwys** [Solaris-Skunk-Werks/sswlib#3]
Alright, on drones we have a slight issue with the BV calculations.

Page 81 (yes I know) states

DRONE REMOTE OPERATING SYSTEMS
All weapons on a unit equipped with a Drone Remote Operating System multiply their BVs by 0.8. Do not include ammunition when making these BV adjustments.
In addition, multiply the final unit BV by 0.95. Do not apply any BV modifiers for cockpits.

Right now, SSW isn't doing any of this.

So the Weapon BV on Drones (They have the Drone OS equipment) in the offensive part of the calculation need to be multiplied by .8 to get a new value. 

Then any modifiers for small cockpits or torso cockpits (or whatever) need to be deleted, and a new modifier of .95 needs to be included at the end where the cockpit modifier normally is.

If need be, I can post a BV calculation to show what I mean.

**Comment by WEKarnesky** [comment]
I believe 0db3d27 fixes this.
